name: pre-commit-dbt
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pre_commit_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit model checks
        run: pre-commit run --files ${{ steps.file_changes.outputs.files}}